spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ordermenue?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/static/
  redis:
    host: localhost
    port: 6379
#  jackson:
#    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

logging:
  level:
    cn.zijun.ordermenue.dataobject.mapper: trace
  file:
    path: D://spring.log

mybatis:
  mapper-locations: classpath:mapper/*.xml

wechat:
  mpAppId: wx70612f74c698c608
  mpAppSecret: d1a858b884c75715048d3b4908dd8776
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://zijunsell.natapp4.cc/sell/pay/notify